var PRODUCER_REGISTRATION_FIRSTNAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>Smith</td></tr></table>";
var PRODUCER_REGISTRATION_LASTNAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>John</td></tr></table>";
var PRODUCER_REGISTRATION_STREET_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>300 Connecticut St</td></tr></table>";
var PRODUCER_REGISTRATION_CITY_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>San Francisco</td></tr></table>";
var PRODUCER_REGISTRATION_ZIP_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>694107</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Must be 6 characters.</td></tr></table>";
var PRODUCER_REGISTRATION_TELEPHONE_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>9999999</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Telephone is required in case there are question about your account.</td></tr></table>";
var PRODUCER_REGISTRATION_EXTENSION_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>999</td></tr></table>";
var PRODUCER_REGISTRATION_YEAR_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>1980</td></tr></table>";
var PRODUCER_REGISTRATION_EMAIL_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Valid Email Address</td></tr><tr><td align='right'><b>Example:</b></td><td>myname@yahoo.com</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Valid email address is required to complete registration.</td></tr></table>";
var PRODUCER_REGISTRATION_PASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Password must be atleast 6 characters long.</td></tr></table>";
var PRODUCER_REGISTRATION_REPASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Re-Password must be matched with the password.</td></tr></table>";
var PRODUCER_REGISTRATION_ANSWER_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>Jack</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>You will be asked for the answer to your secret question if you forget your password.</td></tr></table>";

var CONSUMER_REGISTRATION_FIRSTNAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>Smith</td></tr></table>";
var CONSUMER_REGISTRATION_LASTNAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>John</td></tr></table>";
var CONSUMER_REGISTRATION_STREET_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>300 Connecticut St</td></tr></table>";
var CONSUMER_REGISTRATION_CITY_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>San Francisco</td></tr></table>";
var CONSUMER_REGISTRATION_ZIP_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>694107</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Must be 6 characters.</td></tr></table>";
var CONSUMER_REGISTRATION_TELEPHONE_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>9999999</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Telephone is required in case there are question about your account.</td></tr></table>";
var CONSUMER_REGISTRATION_MOBILENUMBER_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>9999999</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Moblie number is required in case there are question about your account.</td></tr></table>";
var CONSUMER_REGISTRATION_EXTENSION_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>999</td></tr></table>";
var CONSUMER_REGISTRATION_YEAR_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>1980</td></tr></table>";
var CONSUMER_REGISTRATION_EMAIL_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Valid Email Address</td></tr><tr><td align='right'><b>Example:</b></td><td>myname@yahoo.com</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Valid email address is required to complete registration.</td></tr></table>";
var CONSUMER_REGISTRATION_PASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Password must be atleast 6 characters long.</td></tr></table>";
var CONSUMER_REGISTRATION_REPASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Re-Password must be matched with the password.</td></tr></table>";
var CONSUMER_REGISTRATION_ANSWER_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>Jack</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>You will be asked for the answer to your secret question if you forget your password.</td></tr></table>";

var FORGET_PASSWORD_EMAIL_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Valid Email Address</td></tr><tr><td align='right'><b>Example:</b></td><td>myname@yahoo.com</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Email address that you specify during MCE registration.</td></tr></table>";
var FORGET_PASSWORD_ANSWER_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>Jack</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Give the correct answer to the question which you selected during registration.</td></tr></table>";

var CUSTOMER_SIGNIN_EMAIL_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Valid Email Address</td></tr><tr><td align='right'><b>Example:</b></td><td>myname@yahoo.com</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Email address that you specify during MCE registration.</td></tr></table>";
var CUSTOMER_SIGNIN_PASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Password that you specify during MCE registration.</td></tr></table>";

var PRODUCER_ACTIVATION_EMAIL_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Valid Email Address</td></tr><tr><td align='right'><b>Example:</b></td><td>myname@yahoo.com</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Email address that you specify during MCE registration.</td></tr></table>";
var PRODUCER_ACTIVATION_CODE_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>Valid Activation Code</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Activation Code that was sent to you via email.</td></tr></table>";

var CONSUMER_ACTIVATION_EMAIL_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Valid Email Address</td></tr><tr><td align='right'><b>Example:</b></td><td>myname@yahoo.com</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Email address that you specify during MCE registration.</td></tr></table>";
var CONSUMER_ACTIVATION_CODE_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>Valid Activation Code</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Activation Code that was sent to you via email.</td></tr></table>";

var PLACECAST_NAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>USA</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>It can be any of your choice</td></tr></table>";
var PLACECAST_STREET_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>300 Connecticut St</td></tr></table>";
var PLACECAST_CITY_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>San Francisco</td></tr></table>";
var PLACECAST_ZIP_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>694107</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Must be 6 characters.</td></tr></table>";

var WAYPOINT_NAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>USA</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>It can be any of your choice</td></tr></table>";
var WAYPOINT_STREET_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>300 Connecticut St</td></tr></table>";
var WAYPOINT_CITY_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>San Francisco</td></tr></table>";
var WAYPOINT_ZIP_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>694107</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Must be 6 characters.</td></tr></table>";
var ADMIN_SIGNIN_EMAIL_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Valid Email Address</td></tr><tr><td align='right'><b>Example:</b></td><td>admin@mce.com</td></tr></table>";
var ADMIN_SIGNIN_PASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr></table>";
var ADMIN_FORGET_PASSWORD_EMAIL_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Valid Email Address</td></tr><tr><td align='right'><b>Example:</b></td><td>admin@mce.com</td></tr></table>";
var ADMIN_REGISTRATION_PASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Password must be atleast 6 characters long.</td></tr></table>";
var ADMIN_REGISTRATION_REPASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Re-Password must be matched with the password.</td></tr></table>";

var ADMIN_PRODUCER_FIRSTNAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>Smith</td></tr></table>";
var ADMIN_PRODUCER_LASTNAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>John</td></tr></table>";
var ADMIN_PRODUCER_STREET_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>300 Connecticut St</td></tr></table>";
var ADMIN_PRODUCER_CITY_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>San Francisco</td></tr></table>";
var ADMIN_PRODUCER_ZIP_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>694107</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Must be 6 characters.</td></tr></table>";
var ADMIN_PRODUCER_TELEPHONE_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>9999999</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Telephone is required in case there are question about your account.</td></tr></table>";
var ADMIN_PRODUCER_EXTENSION_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>999</td></tr></table>";
var ADMIN_PRODUCER_YEAR_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>1980</td></tr></table>";
var ADMIN_PRODUCER_EMAIL_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Valid Email Address</td></tr><tr><td align='right'><b>Example:</b></td><td>myname@yahoo.com</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Valid email address is required to complete registration.</td></tr></table>";
var ADMIN_PRODUCER_PASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Password must be atleast 6 characters long.</td></tr></table>";
var ADMIN_PRODUCER_REPASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Re-Password must be matched with the password.</td></tr></table>";
var ADMIN_PRODUCER_ANSWER_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>Jack</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>You will be asked for the answer to your secret question if you forget your password.</td></tr></table>";
var ADMIN_PRODUCER_ACTIVATION_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Used for activation of the user.</td></tr></table>";


var ADMIN_CONSUMER_FIRSTNAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>Smith</td></tr></table>";
var ADMIN_CONSUMER_LASTNAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>John</td></tr></table>";
var ADMIN_CONSUMER_STREET_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>300 Connecticut St</td></tr></table>";
var ADMIN_CONSUMER_CITY_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>San Francisco</td></tr></table>";
var ADMIN_CONSUMER_ZIP_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>694107</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Must be 6 characters.</td></tr></table>";
var ADMIN_CONSUMER_TELEPHONE_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>9999999</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Telephone is required in case there are question about your account.</td></tr></table>";
var ADMIN_CONSUMER_EXTENSION_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>999</td></tr></table>";
var ADMIN_CONSUMER_YEAR_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>1980</td></tr></table>";
var ADMIN_CONSUMER_EMAIL_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Valid Email Address</td></tr><tr><td align='right'><b>Example:</b></td><td>myname@yahoo.com</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Valid email address is required to complete registration.</td></tr></table>";
var ADMIN_CONSUMER_PASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Password must be atleast 6 characters long.</td></tr></table>";
var ADMIN_CONSUMER_REPASSWORD_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Re-Password must be matched with the password.</td></tr></table>";
var ADMIN_CONSUMER_ANSWER_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>All Characters</td></tr><tr><td align='right'><b>Example:</b></td><td>Jack</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>You will be asked for the answer to your secret question if you forget your password.</td></tr></table>";
var ADMIN_CONSUMER_ACTIVATION_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Alpha-Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>abc123</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>Used for activation of the user.</td></tr></table>";

var ADMIN_ADD_ADDNAME_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>Valid Characters:</b></td><td>Alphabets</td></tr><tr><td width='107' align='right'><b>Example:</b></td><td width='71'>John</td></tr></table>";
var ADMIN_ADD_YEAR_TOOLTIP="<table class=ToolTipText><tr><td  align='right'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>1980</td></tr></table>";
var WAYPOINT_RADIUS_TOOLTIP="<table class=ToolTipText><tr><td  align='right' width='111'><b>&nbsp;&nbsp;Valid Characters:</b></td><td>Numeric</td></tr><tr><td align='right'><b>Example:</b></td><td>111</td></tr><tr><td  align='right' valign='top'><b>&nbsp;&nbsp;Description:</b></td><td>It will be in meters.</td></tr></table>";